branches:
  only:
    - develop
    
environment:
  access_token:
    # EDIT the encrypted version of your GitHub access token
    secure: EBcZBkkr/hL0OsvPSAq/3/Uf9hCLx9nIbzx9rFm9PbkhLKroE+AXMZ5Y3ZMpKoPN

install:
  - git submodule update --init --recursive
  - mkdir ..\DocBuilder\Wyam
  - mkdir ..\DocBuilder\output
  # Fetch the latest version of Wyam 
  - "curl -s https://raw.githubusercontent.com/Wyamio/Wyam/master/RELEASE -o ..\\DocBuilder\\Wyam\\wyamversion.txt"
  - set /P WYAMVERSION=< ..\DocBuilder\Wyam\wyamversion.txt
  - echo %WYAMVERSION%
  # Get and unzip the latest version of Wyam
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/$env:WYAMVERSION/Wyam-$env:WYAMVERSION.zip" -FileName "..\DocBuilder\Wyam\Wyam.zip"
  - 7z x ..\DocBuilder\Wyam\Wyam.zip -o..\DocBuilder\Wyam -r

build_script:
  - dotnet ..\DocBuilder\Wyam\Wyam.dll --output ..\output  --config .\DocBuilder\config.wyam --input .\DocBuilder

on_success:
  # Switch branches to gh-pages, clean the folder, copy everything in from the Wyam output, and commit/push
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  - git config --global credential.helper store
  # EDIT your Git email and name
  - git config --global user.email "cycleapple@gmail.com"
  - git config --global user.name "Ming Tu"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout gh-pages
  - git rm -rf .
  - xcopy ..\DocBuilder\output . /E
  # EDIT your domain name or remove if not using a custom domain
  - echo ironvulture.github.io > CNAME
  # EDIT the origin of your repository - have to reset it here because AppVeyor pulls from SSH, but GitHub won't accept SSH pushes
  - git remote set-url origin https://github.com/IronVulture/OOOne-Unity-Tools.git
  - git add -A
  - git commit -a -m "Commit from AppVeyor"
  # remove extrafiles created after commit
  - git rm --cached config.wyam.dll
  - git rm --cached config.wyam.hash
  - git rm --cached config.wyam.packages.xml
  - git commit -a -m "Remove Configs"
  - git push