pipeline {
  agent any
  environment {
    GIT = '"C:\\Program Files\\Git\\bin\\git.exe"'
    UNITY = '"C:\\Program Files\\Unity\\Editor\\Unity.exe"'
    PROJECT = 'OOOneUnityTools_Win_Switch'
    PLATFORM = 'Win64'
    OUTPUT = 'Build/OOneUnityTools.exe'
    WORKSPACE = '"C:/Users/builder/AppData/Local/Jenkins/.jenkins/workspace/OOOneUnityTools_Win_Switch"'
  }
  stages {
    stage('Clean Workspace') {
      steps {
        bat "$GIT reset --hard"
        bat "$GIT clean -x -f -d -e $PROJECT/Library"
      }
    }
    stage('Update Workspace') {
      steps {
        bat "$GIT checkout"
        bat "$GIT lfs checkout"
      }
    }
    stage('Import Assets') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$WORKSPACE -quit -accept-apiupdate"
      }
    }
    stage('Run Unit Tests') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$WORKSPACE -runEditorTests -quit"
      }
    }
    stage('Win64_Build') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$WORKSPACE -buildTarget $PLATFORM -quit -buildWindows64Player=$OUTPUT"
      }
    }

    stage('NS_Build') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$WORKSPACE -executeMethod OOOneBuild.AutoBuildScript.BuildGame -quit "
      }
	}
    post {
      always {
      discordSend description: 'OOOneUnityTools_Win_Switch Build', footer: 'Jenkins 2.263.1', link: env.BUILD_URL, result: currentBuild.currentResult, unstable: false, title: OOOneUnityTools_Win_Switch, webhookURL: 'https://discordapp.com/api/webhooks/788020632562302977/MMKmpKHvYt87lAhubWz4eRSumUkQgsrKeh_H3XfF3wJB9PZpCmV9H8xd-pdlfW4p_Mdg'
      }
    }
    
  }
}
