pipeline {
  agent any
  environment {
    GIT = '"C:\\Program Files\\Git\\bin\\git.exe"'
    UNITY = '"C:\\Program Files\\Unity\\Editor\\Unity.exe"'
    PROJECT = 'OOOneUnityTools_Win64'
    PLATFORM = 'Win64'
    OUTPUT = 'Build/OOneUnityTools.exe'
  }
  stages {
    stage('Clean Workspace') {
      steps {
        bat "$GIT reset --hard"
        bat "$GIT clean -x -f -d -e $PROJECT/Library"
      }
    }
    stage('Update Workspace') {
      steps {
        bat "$GIT checkout"
        bat "$GIT lfs checkout"
      }
    }
    stage('Import Assets') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$PROJECT -buildTarget $PLATFORM -quit -accept-apiupdate"
      }
    }
    stage('Run Unit Tests') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$PROJECT -buildTarget $PLATFORM -runEditorTests"
      }
    }
    stage('Build') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$PROJECT -buildTarget $PLATFORM -quit -buildWindows64Player=$OUTPUT"
      }
    }

    stage('NS_Build') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath=$PROJECT -executeMethod OOOneBuild.AutoBuildScript.BuildGame -quit "
      }
    }
  }
}
